### ISSUE TITLE
Current implementation will strip headers with same key

### ISSUE THREAD

**Issue by quangIO** [google/sxg-rs#202]
The [Headers](https://github.com/google/sxg-rs/blob/d0e1374d9d6b5368b175e6ffd2d0482246383ccf/sxg_rs/src/headers.rs#L29) struct uses HashMap to hold key-value pairs. However, headers can have same keys. For conforming headers, we can join them into one string, but it is not the case for all headers, especially when their values can contain comma(s). Thus, sxg-rs should use a multi-map (e.g. HeaderMap in http).

I can help replacing the current implementation if you think it makes sense.

**Comment by twifkak** [comment]
Good catch. Note that the signed exchanges spec [disallows duplicate headers](https://wicg.github.io/webpackage/draft-yasskin-http-origin-signed-responses.html#name-cbor-representation-of-exch), so the processor must join them with a comma before signing.

Note that [`Set-Cookie` can't be joined on comma](https://datatracker.ietf.org/doc/html/rfc7230#section-3.2.2) but that's OK since the SXG spec disallows it anyway. (sxg-rs either strips it or cancels signing, depending on configuration.)

**Comment by quangIO** [comment]
Thank you for the clarification! I just open a small pull request that should support RFC-conforming headers.
